[Variables]
FColor = 188,221,250,150
FFace = Calibri
Firefox = E:\Firefox\firefox.exe

;here is the section about the BookMarks,
;fontf -> the fontface of the marks string
;name -> the bookmark's default name
;url -> the default url of the bookmark 
;color -> the color of the bookmark string
; color1 = R, G, B, transparency.
FontF = Old English Text MT

Name1 = Google
URL1 = https://www.google.com
Color1 = 30,235,156,255

Name2 = Python 100days
URL2 = https://github.com/jackfrued/Python-100-Days/blob/master/Day01-15/02.%E8%AF%AD%E8%A8%80%E5%85%83%E7%B4%A0.md
Color2 = 30,235,156,255

Name3 = BookMark3
URL3 = https://www.zhihu.com/question/26006703
Color3 = 30,235,156,255

Name4 = BookMark4
URL4 = https://www.zhihu.com/question/26006703
Color4 = 30,235,156,255

Name5 = BookMark5
URL5 = https://www.zhihu.com/question/26006703
Color5 = 30,235,156,255

;the Background Setting about
;if u don't wanna show the Background, just change the Parameter `backgroundgroup = Mark_Background` to other value.
;The color1 and color are the controller of the Gradient color of the background.
BackgroundGroup = Mark_Backgroun
Backgroundcolor1 = 255, 255, 255, 140
Backgroundcolor2 = 0, 0, 0, 10

;unuseful Parameter, don't delete it, 
;please.
tempmeasure = temp
;
;!CommandMeasure: Skin "github学习   https://zh.wikipedia.org/wiki/%E5%AF%BC%E6%95%B0%E5%88%97%E8%A1%A8" not found (BookMarks\Main.ini)
;
;Warning:
;If u didn't input the URL, the parameter 'URL' won't work correctly!!!